version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-

          - run: ./gradlew check
          - run:
              name: github creds
              command: |
                set -e
                git clone https://github.com/navikt/github-apps-support.git
                export PATH=`pwd`/github-apps-support/bin:$PATH
                echo $DP_CI_KEY | tr '_' '\n' > dpci.key
                export GITHUB_APP_ID=19726
                export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh dpci.key $GITHUB_APP_ID`)
                echo -e "machine api.github.com login x-access-token password $GH_TOKEN" > ~/.netrc
                rm dpci.key

          - save_cache:
              paths:
                - ~/.gradle/caches/
                - ~/.gradle/wrapper/
              key: v1-dependencies-{{ checksum "build.gradle.kts" }}