version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-

      - run: sed s/^'val libVersion.*'/'val libVersion'='"'$CIRCLE_SHA1'"'/ build.gradle.kts > build.gradle.new
            && mv build.gradle.new build.gradle.kts
      - run: ./gradlew check
      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}