version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-

      - run: ./gradlew check

      - store_test_results:
          path: test-results

      - save_cache:
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
  deploy:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      - RELEASE_VERSION: '"1.$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M).$(git rev-parse --short=12 HEAD)"'
      - COMMIT_MESSAGE: '"$(git log --format=%B -n 1 $CIRCLE_SHA1)"'
      - GITHUB_APP_ID: 21626
    steps:
      - checkout
      - run:
          name: github creds
          command: |
            set -e
            git clone https://github.com/navikt/github-apps-support.git
            export PATH=`pwd`/github-apps-support/bin:$PATH
            echo $DP_CI_KEY | tr '_' '\n' > dpci.key
            export GITHUB_APP_ID=19726
            export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh dpci.key $GITHUB_APP_ID`)
            rm dpci.key
      - run:
          command: |
            jq -n --arg tag_name "$RELEASE_VERSION" --arg body "$COMMIT_MESSAGE" '{ "tag_name": $tag_name, "target_commitish": "master", "name": $tag_name, body: $body }' >> release.json
            curl -X POST -H "Authorization: token $GH_TOKEN"  https://api.github.com/repos/navikt/dp-biblioteker/releases --data @release.json



workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
