version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-

      - run:
          command:
            - ./gradlew check


      - save_cache:
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}