name: reviewdog
on: [push]

jobs:
  code-style-violations:
    name: Check coding style violations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check